---
title: "Lab 01 - Hello R"
author: "Alexander Connolly"
date: "1/20/2022"
output: 
  html_document: 
    fig_width: 9
    fig_height: 7
    highlight: haddock
---

## Load packages and data

```{r load-packages, message=FALSE}
library(tidyverse) 
library(datasauRus)
```

## Exercises

### Exercise 1

```{r}
datasaurus_dozen %>%
  count(dataset) %>%
  print(13)
```

### Exercise 2

```{r plot-dino, fig.height=5, fig.width=10}
dino_data <- datasaurus_dozen %>%
  filter(dataset == "dino")

ggplot(data = dino_data, mapping = aes(x = x, y = y)) +
  geom_point()
```

```{r cor-dino}
dino_data %>%
  summarize(r = cor(x, y))
```

### Exercise 3

```{r plot-star}
star_data <- datasaurus_dozen %>%
filter(dataset == "star")
ggplot(data = star_data, mapping = aes(x=y, y=y)) +
geom_point()

```

```{r cor-star}
star_data %>%
summarize(r=cor(x,y))
```

R(star) = -.0629611 vs R(dino) = -.06447185

They are almost the same!

### Exercise 4

```{r plot-circle}
circle_data <- datasaurus_dozen %>%
  filter(dataset == "circle")

ggplot(data=circle_data, mapping =aes(x=y, y=y)) +geom_point()
```

```{r cor-circle}
circle_data %>%
  summarize(r=cor(x,y))
```

r(circle) = -.06834336 vs r(dino) = -.06447185

They are almost the same!

### Exercise 5

```{r}
ggplot(datasaurus_dozen, aes(x = x, y= y,color = dataset)) +
  geom_point()+
  facet_wrap(~ dataset, ncol=3) +
  theme(legend.position = "none")
```

```{r}
datasaurus_dozen %>%
  group_by (dataset) %>%
  summarize(r=cor(x,y)) %>%
  print(13)
```

Done :)
